/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerificarBlogRouteImport } from './routes/_authenticated/verificar-blog'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPaginasRouteImport } from './routes/_authenticated/paginas'
import { Route as AuthenticatedMonetizacaoRouteImport } from './routes/_authenticated/monetizacao'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLibraryIdRouteImport } from './routes/_authenticated/library.$id'
import { Route as AuthenticatedBloggerCallbackRouteImport } from './routes/_authenticated/blogger.callback'
import { Route as ApiPublicWebhooksSyncpayRouteImport } from './routes/api/public/webhooks/syncpay'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerificarBlogRoute =
  AuthenticatedVerificarBlogRouteImport.update({
    id: '/verificar-blog',
    path: '/verificar-blog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaginasRoute = AuthenticatedPaginasRouteImport.update({
  id: '/paginas',
  path: '/paginas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonetizacaoRoute =
  AuthenticatedMonetizacaoRouteImport.update({
    id: '/monetizacao',
    path: '/monetizacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryIdRoute = AuthenticatedLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLibraryRoute,
} as any)
const AuthenticatedBloggerCallbackRoute =
  AuthenticatedBloggerCallbackRouteImport.update({
    id: '/blogger/callback',
    path: '/blogger/callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebhooksSyncpayRoute =
  ApiPublicWebhooksSyncpayRouteImport.update({
    id: '/api/public/webhooks/syncpay',
    path: '/api/public/webhooks/syncpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/monetizacao': typeof AuthenticatedMonetizacaoRoute
  '/paginas': typeof AuthenticatedPaginasRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/verificar-blog': typeof AuthenticatedVerificarBlogRoute
  '/blogger/callback': typeof AuthenticatedBloggerCallbackRoute
  '/library/$id': typeof AuthenticatedLibraryIdRoute
  '/api/public/webhooks/syncpay': typeof ApiPublicWebhooksSyncpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/monetizacao': typeof AuthenticatedMonetizacaoRoute
  '/paginas': typeof AuthenticatedPaginasRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/verificar-blog': typeof AuthenticatedVerificarBlogRoute
  '/blogger/callback': typeof AuthenticatedBloggerCallbackRoute
  '/library/$id': typeof AuthenticatedLibraryIdRoute
  '/api/public/webhooks/syncpay': typeof ApiPublicWebhooksSyncpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/monetizacao': typeof AuthenticatedMonetizacaoRoute
  '/_authenticated/paginas': typeof AuthenticatedPaginasRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/verificar-blog': typeof AuthenticatedVerificarBlogRoute
  '/_authenticated/blogger/callback': typeof AuthenticatedBloggerCallbackRoute
  '/_authenticated/library/$id': typeof AuthenticatedLibraryIdRoute
  '/api/public/webhooks/syncpay': typeof ApiPublicWebhooksSyncpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/connections'
    | '/dashboard'
    | '/financeiro'
    | '/generate'
    | '/library'
    | '/monetizacao'
    | '/paginas'
    | '/pricing'
    | '/verificar-blog'
    | '/blogger/callback'
    | '/library/$id'
    | '/api/public/webhooks/syncpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/connections'
    | '/dashboard'
    | '/financeiro'
    | '/generate'
    | '/library'
    | '/monetizacao'
    | '/paginas'
    | '/pricing'
    | '/verificar-blog'
    | '/blogger/callback'
    | '/library/$id'
    | '/api/public/webhooks/syncpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/connections'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/generate'
    | '/_authenticated/library'
    | '/_authenticated/monetizacao'
    | '/_authenticated/paginas'
    | '/_authenticated/pricing'
    | '/_authenticated/verificar-blog'
    | '/_authenticated/blogger/callback'
    | '/_authenticated/library/$id'
    | '/api/public/webhooks/syncpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicWebhooksSyncpayRoute: typeof ApiPublicWebhooksSyncpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verificar-blog': {
      id: '/_authenticated/verificar-blog'
      path: '/verificar-blog'
      fullPath: '/verificar-blog'
      preLoaderRoute: typeof AuthenticatedVerificarBlogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paginas': {
      id: '/_authenticated/paginas'
      path: '/paginas'
      fullPath: '/paginas'
      preLoaderRoute: typeof AuthenticatedPaginasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monetizacao': {
      id: '/_authenticated/monetizacao'
      path: '/monetizacao'
      fullPath: '/monetizacao'
      preLoaderRoute: typeof AuthenticatedMonetizacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$id': {
      id: '/_authenticated/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AuthenticatedLibraryIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/blogger/callback': {
      id: '/_authenticated/blogger/callback'
      path: '/blogger/callback'
      fullPath: '/blogger/callback'
      preLoaderRoute: typeof AuthenticatedBloggerCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/syncpay': {
      id: '/api/public/webhooks/syncpay'
      path: '/api/public/webhooks/syncpay'
      fullPath: '/api/public/webhooks/syncpay'
      preLoaderRoute: typeof ApiPublicWebhooksSyncpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryIdRoute: typeof AuthenticatedLibraryIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryIdRoute: AuthenticatedLibraryIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedMonetizacaoRoute: typeof AuthenticatedMonetizacaoRoute
  AuthenticatedPaginasRoute: typeof AuthenticatedPaginasRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedVerificarBlogRoute: typeof AuthenticatedVerificarBlogRoute
  AuthenticatedBloggerCallbackRoute: typeof AuthenticatedBloggerCallbackRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedMonetizacaoRoute: AuthenticatedMonetizacaoRoute,
  AuthenticatedPaginasRoute: AuthenticatedPaginasRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedVerificarBlogRoute: AuthenticatedVerificarBlogRoute,
  AuthenticatedBloggerCallbackRoute: AuthenticatedBloggerCallbackRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicWebhooksSyncpayRoute: ApiPublicWebhooksSyncpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
